-- Isolated H2 fixture mirroring the current V23 core/chat/document schema.
-- This is test data setup, not an alternative production migration history.
-- Expression indexes are adapted by AccountApplicationTestDatabase for H2.
-- Only zero-balance system accounts are seeded. No customer or monetary fixtures.
CREATE TABLE customers (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR2(26),
    full_name VARCHAR2(160) NOT NULL,
    email VARCHAR2(254) NOT NULL,
    phone_number VARCHAR2(32),
    date_of_birth DATE,
    address VARCHAR2(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    status VARCHAR2(24) DEFAULT 'ACTIVE' NOT NULL,
    role VARCHAR2(24) DEFAULT 'CUSTOMER' NOT NULL,
    CONSTRAINT uk_customer_user_id UNIQUE (user_id),
    CONSTRAINT uk_customer_email UNIQUE (email),
    CONSTRAINT uk_customer_phone UNIQUE (phone_number),
    CONSTRAINT ck_customer_access_status CHECK (status IN ('ACTIVE','LOCKED','DISABLED')),
    CONSTRAINT ck_customer_access_role CHECK (role IN ('CUSTOMER','SUPPORT_AGENT','FRAUD_ANALYST','ADMIN'))
);

CREATE UNIQUE INDEX uk_customer_email_ci ON customers (LOWER(email));

-- Password hashes and revocable refresh-token hashes share one typed table.
-- No plaintext passwords or bootstrap/demo users belong in this migration.
CREATE TABLE customer_credentials (
    id VARCHAR2(26) PRIMARY KEY,
    user_id VARCHAR2(26) NOT NULL,
    credential_type VARCHAR2(16) NOT NULL,
    password_hash VARCHAR2(100),
    token_hash CHAR(64),
    expires_at TIMESTAMP WITH TIME ZONE,
    revoked_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_credential_customer FOREIGN KEY (user_id) REFERENCES customers (user_id),
    CONSTRAINT uk_credential_token_hash UNIQUE (token_hash),
    CONSTRAINT ck_credential_type CHECK (credential_type IN ('PASSWORD','REFRESH')),
    CONSTRAINT ck_credential_shape CHECK (
        (credential_type='PASSWORD' AND token_hash IS NULL) OR
        (credential_type='REFRESH' AND password_hash IS NULL AND token_hash IS NOT NULL AND expires_at IS NOT NULL)
    )
);

CREATE UNIQUE INDEX uk_password_customer ON customer_credentials (
    CASE WHEN credential_type='PASSWORD' THEN user_id END
);
CREATE INDEX idx_credentials_customer ON customer_credentials (user_id);

-- Deposit accounts, loan/card products and internal cash/clearing accounts.
-- Product-only fields are nullable for ordinary deposit and system accounts.
CREATE TABLE accounts (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_number VARCHAR2(30) NOT NULL,
    customer_id NUMBER,
    account_name VARCHAR2(120) NOT NULL,
    account_type VARCHAR2(20) NOT NULL,
    account_category VARCHAR2(20) NOT NULL,
    currency_code VARCHAR2(3) DEFAULT 'INR' NOT NULL,
    version NUMBER(19) DEFAULT 0 NOT NULL,
    balance NUMBER(19,2) DEFAULT 0 NOT NULL,
    status VARCHAR2(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    product_id VARCHAR2(40),
    funding_account_id NUMBER,
    principal_amount NUMBER(19,2),
    interest_rate NUMBER(9,6),
    product_status VARCHAR2(32),
    product_type VARCHAR2(32),
    number_masked VARCHAR2(40),
    due_at VARCHAR2(40),
    periodic_payment NUMBER(19,2),
    credit_limit NUMBER(19,2),
    minimum_payment NUMBER(19,2),
    application_key VARCHAR2(80),
    loan_purpose VARCHAR2(200),
    tenure_months NUMBER(10),
    approved_at TIMESTAMP,
    closed_at TIMESTAMP,
    reviewed_by VARCHAR2(26),
    review_reason VARCHAR2(500),
    reviewed_at TIMESTAMP,
    CONSTRAINT uk_account_number UNIQUE (account_number),
    CONSTRAINT uk_account_product UNIQUE (product_id),
    CONSTRAINT fk_accounts_customer FOREIGN KEY (customer_id) REFERENCES customers (id),
    CONSTRAINT fk_accounts_funding FOREIGN KEY (funding_account_id) REFERENCES accounts (id),
    CONSTRAINT fk_accounts_reviewer FOREIGN KEY (reviewed_by) REFERENCES customers (user_id),
    CONSTRAINT ck_accounts_type CHECK (account_type IN ('SAVINGS','CURRENT','CASH','CLEARING','LOAN','CARD')),
    CONSTRAINT ck_accounts_category CHECK (account_category IN ('CUSTOMER','SYSTEM')),
    CONSTRAINT ck_accounts_status CHECK (status IN ('ACTIVE','BLOCKED','CLOSED')),
    CONSTRAINT ck_system_account_customer CHECK (
        (account_category='SYSTEM' AND customer_id IS NULL) OR
        (account_category='CUSTOMER' AND customer_id IS NOT NULL)
    ),
    CONSTRAINT ck_loan_values CHECK (
        account_type <> 'LOAN' OR
        (account_category='CUSTOMER' AND principal_amount>0 AND interest_rate>=0 AND balance>=0)
    ),
    CONSTRAINT ck_loan_terms CHECK (
        tenure_months IS NULL OR
        (account_type='LOAN' AND application_key IS NOT NULL AND loan_purpose IS NOT NULL
         AND tenure_months BETWEEN 1 AND 60 AND principal_amount BETWEEN 1000 AND 1000000
         AND interest_rate BETWEEN 0 AND 50 AND periodic_payment>0
         AND (product_status IN ('PENDING_APPROVAL','REJECTED') OR approved_at IS NOT NULL))
    )
);

CREATE INDEX idx_accounts_customer ON accounts (customer_id);
CREATE UNIQUE INDEX uk_loan_application ON accounts (
    CASE WHEN application_key IS NOT NULL THEN customer_id END, application_key
);
CREATE INDEX idx_loan_review_queue ON accounts (account_type, product_status, created_at);

-- PAYMENT rows represent money movements. Other record kinds are instructions,
-- reviews, product schedules or audit events; they are not ledger postings.
CREATE TABLE transactions (
    id VARCHAR2(40) PRIMARY KEY,
    transaction_type VARCHAR2(20),
    source_account_id NUMBER,
    destination_account_id NUMBER,
    merchant_name VARCHAR2(200),
    category VARCHAR2(80),
    payment_method VARCHAR2(32),
    amount NUMBER(19,2),
    status VARCHAR2(32) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    record_kind VARCHAR2(32) DEFAULT 'PAYMENT' NOT NULL,
    user_id VARCHAR2(26),
    parent_id VARCHAR2(40),
    operation VARCHAR2(40),
    target_id VARCHAR2(80),
    transaction_reference VARCHAR2(80),
    minimum_amount NUMBER(19,2),
    currency_code VARCHAR2(3),
    display_name VARCHAR2(200),
    source_name VARCHAR2(120),
    source_masked VARCHAR2(40),
    recipient_name VARCHAR2(160),
    destination_masked VARCHAR2(40),
    bank_name VARCHAR2(160),
    destination_hash VARCHAR2(64),
    routing_code VARCHAR2(32),
    beneficiary_type VARCHAR2(24),
    frequency VARCHAR2(32),
    effective_date VARCHAR2(40),
    end_date VARCHAR2(40),
    due_at VARCHAR2(40),
    expires_at TIMESTAMP,
    updated_at TIMESTAMP,
    audit_reason VARCHAR2(500),
    before_name VARCHAR2(120),
    after_name VARCHAR2(120),
    before_status VARCHAR2(32),
    after_status VARCHAR2(32),
    installment_number NUMBER(10),
    principal_component NUMBER(19,2),
    interest_component NUMBER(19,2),
    CONSTRAINT fk_tx_source FOREIGN KEY (source_account_id) REFERENCES accounts (id),
    CONSTRAINT fk_tx_destination FOREIGN KEY (destination_account_id) REFERENCES accounts (id),
    CONSTRAINT fk_tx_customer FOREIGN KEY (user_id) REFERENCES customers (user_id),
    CONSTRAINT fk_tx_parent FOREIGN KEY (parent_id) REFERENCES transactions (id),
    CONSTRAINT ck_tx_record_kind CHECK (record_kind IN (
        'PAYMENT','MANDATE','MANDATE_EVENT','BILL','SCHEDULED_PAYMENT','BENEFICIARY',
        'TRANSFER_REVIEW','SIMULATION','LEGACY_TRANSFER','PRODUCT_HISTORY','ADMIN_EVENT','LOAN_INSTALLMENT'
    )),
    CONSTRAINT ck_payment_shape CHECK (
        record_kind <> 'PAYMENT' OR
        (amount IS NOT NULL AND amount>0 AND transaction_type IS NOT NULL
         AND transaction_type IN ('DEPOSIT','WITHDRAWAL','TRANSFER','LOAN_DISBURSEMENT','LOAN_REPAYMENT')
         AND status IN ('SUCCESS','FAILED','REVERSED')
         AND (source_account_id IS NOT NULL OR destination_account_id IS NOT NULL))
    ),
    CONSTRAINT ck_instruction_owner CHECK (record_kind='PAYMENT' OR user_id IS NOT NULL),
    CONSTRAINT ck_posting_accounts CHECK (
        record_kind <> 'PAYMENT' OR
        (transaction_type='DEPOSIT' AND source_account_id IS NULL AND destination_account_id IS NOT NULL) OR
        (transaction_type='WITHDRAWAL' AND source_account_id IS NOT NULL AND destination_account_id IS NULL) OR
        (transaction_type IN ('TRANSFER','LOAN_DISBURSEMENT','LOAN_REPAYMENT')
         AND source_account_id IS NOT NULL AND destination_account_id IS NOT NULL
         AND source_account_id<>destination_account_id)
    ),
    CONSTRAINT ck_mandate_authorization CHECK (
        record_kind <> 'MANDATE' OR operation IS NULL OR
        (operation='TRANSFER' AND source_account_id IS NOT NULL AND destination_account_id IS NOT NULL
         AND source_account_id<>destination_account_id AND amount IS NOT NULL AND amount>0
         AND effective_date IS NOT NULL)
    ),
    CONSTRAINT ck_review_shape CHECK (
        record_kind <> 'TRANSFER_REVIEW' OR
        (source_account_id IS NOT NULL AND destination_account_id IS NOT NULL
         AND source_account_id<>destination_account_id AND amount IS NOT NULL AND amount>0
         AND expires_at IS NOT NULL AND
         ((status IN ('READY','CANCELLED') AND transaction_reference IS NULL AND completed_at IS NULL) OR
          (status='COMPLETED' AND transaction_reference IS NOT NULL AND completed_at IS NOT NULL)))
    ),
    CONSTRAINT ck_loan_installment CHECK (
        record_kind <> 'LOAN_INSTALLMENT' OR
        (target_id IS NOT NULL AND installment_number BETWEEN 1 AND 60 AND due_at IS NOT NULL
         AND principal_component IS NOT NULL AND principal_component>0
         AND interest_component IS NOT NULL AND interest_component>=0
         AND amount=principal_component+interest_component AND status IN ('PENDING','PAID'))
    )
);

CREATE INDEX idx_tx_source ON transactions (source_account_id);
CREATE INDEX idx_tx_destination ON transactions (destination_account_id);
CREATE INDEX idx_tx_owner_kind ON transactions (user_id, record_kind, created_at);
CREATE INDEX idx_tx_parent ON transactions (parent_id);
CREATE INDEX idx_product_history ON transactions (target_id, record_kind, created_at);
CREATE INDEX idx_admin_account_audit ON transactions (record_kind, source_account_id, created_at);
CREATE UNIQUE INDEX uk_review_payment ON transactions (
    CASE WHEN record_kind='TRANSFER_REVIEW' THEN transaction_reference END
);
CREATE UNIQUE INDEX uk_beneficiary_destination ON transactions (
    CASE WHEN record_kind='BENEFICIARY' THEN user_id END,
    CASE WHEN record_kind='BENEFICIARY' THEN destination_hash END
);
CREATE UNIQUE INDEX uk_loan_installment ON transactions (
    CASE WHEN installment_number IS NOT NULL THEN target_id END, installment_number
);

-- One journal per financial transaction; a journal can contain more than two
-- postings (for example loan principal, funding-control and interest entries).
CREATE TABLE journal_entries (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id VARCHAR2(40) NOT NULL,
    entry_reference VARCHAR2(40) NOT NULL,
    entry_type VARCHAR2(20) NOT NULL,
    status VARCHAR2(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_journal_transaction UNIQUE (transaction_id),
    CONSTRAINT uk_journal_reference UNIQUE (entry_reference),
    CONSTRAINT fk_journal_transaction FOREIGN KEY (transaction_id) REFERENCES transactions (id),
    CONSTRAINT ck_journal_type CHECK (entry_type IN ('TRANSACTION','REVERSAL')),
    CONSTRAINT ck_journal_status CHECK (status IN ('POSTED','REVERSED'))
);

CREATE TABLE ledger_entries (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journal_entry_id NUMBER NOT NULL,
    account_id NUMBER NOT NULL,
    entry_type VARCHAR2(10) NOT NULL,
    amount NUMBER(19,2) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_ledger_journal FOREIGN KEY (journal_entry_id) REFERENCES journal_entries (id),
    CONSTRAINT fk_ledger_account FOREIGN KEY (account_id) REFERENCES accounts (id),
    CONSTRAINT ck_ledger_type CHECK (entry_type IN ('DEBIT','CREDIT')),
    CONSTRAINT ck_ledger_amount CHECK (amount>0)
);

CREATE INDEX idx_ledger_account ON ledger_entries (account_id);
CREATE INDEX idx_ledger_journal ON ledger_entries (journal_entry_id);

-- Required infrastructure accounts only. Starting balances are zero: this
-- creates no customer money, deposits, loans, journals or administrator login.
-- Loan disbursement intentionally remains unavailable until the bank funding
-- account is capitalized through an authorized, balanced posting workflow.
INSERT INTO accounts (
    account_number, account_name, account_type, account_category,
    currency_code, balance, status, version, created_at, updated_at
) VALUES (
    'SYSTEM-CASH', 'System cash account', 'CASH', 'SYSTEM',
    'INR', 0, 'ACTIVE', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);

INSERT INTO accounts (
    account_number, account_name, account_type, account_category,
    currency_code, balance, status, version, created_at, updated_at
) VALUES (
    'NEXA-LOAN-INTEREST', 'Loan interest income', 'CLEARING', 'SYSTEM',
    'INR', 0, 'ACTIVE', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);

INSERT INTO accounts (
    account_number, account_name, account_type, account_category,
    currency_code, balance, status, version, created_at, updated_at
) VALUES (
    'NEXA-BANK-FUNDING', 'Nexa Bank funding and repayments', 'CLEARING', 'SYSTEM',
    'INR', 0, 'ACTIVE', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);

INSERT INTO accounts (
    account_number, account_name, account_type, account_category,
    currency_code, balance, status, version, created_at, updated_at
) VALUES (
    'NEXA-LOAN-CONTROL', 'Bank loan funding control', 'CLEARING', 'SYSTEM',
    'INR', 0, 'ACTIVE', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);

-- CHAT AND WORKFLOW SUPPORT (four tables, in addition to the six banking tables).
-- Create CUSTOMERS first; its USER_ID must have a unique or primary-key constraint.
-- Mirrors the current V7, V8, V12, V13 and V16 conversation schema.
-- No legacy USERS table, copy-forward operations, demo customers or demo credentials.

-- A customer owns a conversation. Deleting a customer is not cascaded through chat.
CREATE TABLE conversations (
    id VARCHAR2(36) PRIMARY KEY,
    user_id VARCHAR2(26) NOT NULL,
    title VARCHAR2(120 CHAR) DEFAULT 'New conversation' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_chat_customer FOREIGN KEY (user_id) REFERENCES customers(user_id)
);
CREATE INDEX ix_conversations_owner ON conversations(user_id, created_at DESC, id);

-- Each row is one exchange, with an optional versioned banking/workflow snapshot.
-- The unique client ID per conversation makes retries idempotent. The identity
-- sequence supplies ordering; the Java API returns it as text for JS precision.
-- Deleting chat removes its turns, but never financial records or action audit.
CREATE TABLE conversation_turns (
    sequence_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    conversation_id VARCHAR2(36) NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    client_id VARCHAR2(36) NOT NULL,
    source VARCHAR2(5) NOT NULL CHECK (source IN ('TEXT', 'VOICE')),
    intent VARCHAR2(40) NOT NULL,
    user_text CLOB NOT NULL,
    assistant_text CLOB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    banking_content CLOB,
    workflow_content CLOB,
    CONSTRAINT uk_conversation_turn_retry UNIQUE (conversation_id, client_id),
    CONSTRAINT ck_turn_banking_json CHECK (banking_content IS JSON)
);
CREATE INDEX ix_conversation_turn_page ON conversation_turns(conversation_id, sequence_id DESC);

-- Mutable workflow state for draft/review/confirmation UI. It is not a ledger.
-- Like turns, this state is removed when its parent conversation is deleted.
CREATE TABLE conversation_workflows (
    id VARCHAR2(36) PRIMARY KEY,
    conversation_id VARCHAR2(36) NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    state CLOB NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX idx_workflow_conversation ON conversation_workflows(conversation_id, updated_at);

-- Intentionally independent of deletable conversations and workflow rows.
-- No foreign key to either: audit events must survive deletion of chat history.
-- IDs, operation/status and masked references are retained, not raw message text.
-- AMOUNT is the workflow's textual snapshot, not an authoritative money column.
CREATE TABLE conversation_action_events (
    id VARCHAR2(36) PRIMARY KEY,
    action_id VARCHAR2(36) NOT NULL,
    user_id VARCHAR2(26) NOT NULL,
    operation VARCHAR2(40) NOT NULL,
    status VARCHAR2(24) NOT NULL,
    source_account_id VARCHAR2(80),
    target_id VARCHAR2(80),
    amount VARCHAR2(32),
    transaction_reference VARCHAR2(80),
    correlation_id VARCHAR2(128),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX idx_action_audit ON conversation_action_events(action_id, created_at);


-- Private supporting documents, never served from a public/static directory.
CREATE TABLE loan_salary_slips (
 id VARCHAR2(40) PRIMARY KEY,
 loan_account_id NUMBER NOT NULL REFERENCES accounts(id),
 salary_month VARCHAR2(7) NOT NULL,
 file_name VARCHAR2(160) NOT NULL,
 media_type VARCHAR2(80) NOT NULL,
 file_size NUMBER(10) NOT NULL,
 sha256 VARCHAR2(64) NOT NULL,
 file_content BLOB NOT NULL,
 uploaded_at TIMESTAMP NOT NULL,
 verified_by VARCHAR2(26) REFERENCES customers(user_id),
 verified_at TIMESTAMP,
 CONSTRAINT uk_loan_salary_month UNIQUE (loan_account_id, salary_month),
 CONSTRAINT uk_loan_salary_content UNIQUE (loan_account_id, sha256),
 CONSTRAINT ck_loan_salary_size CHECK (file_size BETWEEN 1 AND 5242880)
);

