/** UI language only. Never rewrites API commands, identifiers or server narratives. */
export type Locale = "en-IN" | "hi-IN";
let locale: Locale = "en-IN";
try { if (window.localStorage?.getItem("nexa-language") === "hi-IN") locale = "hi-IN"; } catch { /* Storage is optional. */ }
export const getLocale = () => locale;
export function setLocale(value: Locale) {
  locale = value;
  try { window.localStorage?.setItem("nexa-language", value); } catch { /* Keep the in-memory preference. */ }
  if (typeof document !== "undefined") document.documentElement.lang = value;
  if (typeof window !== "undefined" && window.dispatchEvent) window.dispatchEvent(new Event("nexa-language-change"));
}

const hindi: Record<string, string> = {
  "Home": "होम", "Accounts": "खाते", "Payments": "भुगतान", "Cards": "कार्ड", "Transactions": "लेन-देन", "Insights": "खर्च का विश्लेषण", "Support": "सहायता",
  "Personal banking": "व्यक्तिगत बैंकिंग", "Your banking": "आपकी बैंकिंग", "Your money, in conversation.": "आपके पैसे की बात, आपकी भाषा में।",
  "A little clarity. A lot more possibility.": "पैसों की जानकारी, अब और आसान।", "Ask a question, make a plan, or get something done.": "सवाल पूछें, योजना बनाएँ या अपना बैंकिंग काम पूरा करें।",
  "EVERYDAY, MADE EASIER": "रोज़मर्रा की बैंकिंग, अब आसान", "Available balance": "उपलब्ध बैलेंस", "Account balances": "खातों का बैलेंस",
  "At a glance": "एक नज़र में", "Your accounts": "आपके खाते", "Hide balances": "बैलेंस छिपाएँ", "Show balances": "बैलेंस दिखाएँ", "Account context": "खातों की जानकारी", "Close account context": "खातों की जानकारी बंद करें",
  "Open accounts": "खाते खोलें", "View transactions": "लेन-देन देखें", "Current balance": "वर्तमान बैलेंस", "Balances hidden": "बैलेंस छिपा हुआ है",
  "Money moves only after you confirm.": "आपकी पुष्टि के बाद ही पैसे भेजे जाते हैं।", "Review before you send": "भेजने से पहले जाँचें", "Check the recipient and amount before confirming a payment.": "भुगतान की पुष्टि से पहले प्राप्तकर्ता और राशि जाँचें।",
  "Conversations": "बातचीत", "Recent conversations": "हाल की बातचीत", "New conversation": "नई बातचीत", "Close history": "इतिहास बंद करें", "Conversation history": "बातचीत का इतिहास", "Conversation options": "बातचीत के विकल्प",
  "Your conversations will appear here.": "आपकी बातचीत यहाँ दिखाई देगी।", "Load more conversations": "और बातचीत दिखाएँ", "Load earlier messages": "पुराने संदेश दिखाएँ", "Loading conversation…": "बातचीत लोड हो रही है…",
  "Banking details": "बैंकिंग विवरण", "All banking details": "सभी बैंकिंग विवरण", "Profile & security": "प्रोफ़ाइल और सुरक्षा", "Bills": "बिल", "Banking": "बैंकिंग", "History": "इतिहास", "Options": "विकल्प",
  "Working on your request…": "आपके अनुरोध पर काम हो रहा है…", "Your banking starts here.": "आपकी बैंकिंग यहाँ से शुरू होती है।", "Open banking overview": "बैंकिंग विवरण खोलें", "Nexa banking conversation": "Nexa बैंकिंग बातचीत",
  "Messages": "संदेश", "Conversation messages": "बातचीत के संदेश", "Your message": "आपका संदेश", "Nexa’s message": "Nexa का संदेश", "Nexa’s banking response": "Nexa का बैंकिंग जवाब", "Understood from speech": "आवाज़ से समझा गया",
  "Saved": "सहेजा गया", "Sending…": "भेजा जा रहा है…", "Not confirmed": "पुष्टि नहीं हुई", "Finding your answer…": "आपका जवाब खोज रहे हैं…", "New messages": "नए संदेश",
  "Read replies aloud": "जवाब सुनाएँ", "Turn off spoken replies": "जवाब सुनाना बंद करें", "Read last reply": "पिछला जवाब सुनाएँ", "Stop reading replies": "जवाब सुनाना बंद करें", "Sign out": "साइन आउट",
  "Delete conversation": "बातचीत मिटाएँ", "Keep conversation": "बातचीत रखें", "Confirm delete": "मिटाने की पुष्टि करें", "Deleting…": "मिटाया जा रहा है…", "Confirm deletion": "मिटाने की पुष्टि",
  "Delete this conversation and its messages? This cannot be undone.": "इस बातचीत और इसके संदेशों को मिटाएँ? इसे वापस नहीं लाया जा सकेगा।", "Your unsent draft will also be removed.": "आपका न भेजा गया संदेश भी मिट जाएगा।",
  "Couldn’t delete this conversation. Please try again.": "बातचीत मिटाई नहीं जा सकी। फिर कोशिश करें।", "Try again": "फिर कोशिश करें", "Try loading again": "फिर लोड करें", "Remove message": "संदेश हटाएँ",
  "Check Balance": "बैलेंस देखें", "Send Money": "पैसे भेजें", "Recent Transactions": "हाल के लेन-देन", "Get Help": "मदद लें", "Banking quick actions": "बैंकिंग के आसान विकल्प",
  "What’s my balance?": "मेरा बैलेंस कितना है?", "Show my latest transactions": "मेरे हाल के लेनदेन दिखाओ।", "Move money between my accounts": "मेरे खातों के बीच पैसे भेजें", "Understand my spending": "मेरे खर्च को समझें",
  "See what’s available across your accounts": "अपने खातों में उपलब्ध राशि देखें", "A closer look at money in and out": "आने और जाने वाले पैसों की जानकारी", "Review a transfer before sending": "भेजने से पहले ट्रांसफ़र जाँचें", "Explore your spending by category": "श्रेणी के अनुसार अपना खर्च देखें",
  "Write your question": "अपना सवाल लिखें", "Ask about your money, or tell me what you’d like to do…": "पैसों के बारे में पूछें या बताएँ कि आप क्या करना चाहते हैं…", "Ask Nexa…": "Nexa से पूछें…", "Speak your message": "अपना संदेश बोलें", "Speak": "बोलें", "Send": "भेजें", "Send message": "संदेश भेजें",
  "Language": "भाषा", "Voice language / बोलने की भाषा": "भाषा / Language", "Use suggested message": "सुझाया गया संदेश इस्तेमाल करें", "About voice": "आवाज़ के बारे में", "Type instead": "लिखकर पूछें",
  "Speak, then check your words before sending.": "बोलें, फिर भेजने से पहले अपने शब्द जाँचें।", "Review your words before sending. Speech recognition may use your browser’s speech service.": "भेजने से पहले शब्द जाँचें। आवाज़ पहचानने के लिए ब्राउज़र की स्पीच सेवा इस्तेमाल हो सकती है।",
  "Message ready": "संदेश तैयार है", "Voice message ready": "आवाज़ का संदेश तैयार है", "Finishing…": "शब्द तैयार हो रहे हैं…", "Listening": "सुन रहे हैं", "Check your words before sending": "भेजने से पहले अपने शब्द जाँचें", "Your voice message": "आपका आवाज़ का संदेश", "Cancel": "रद्द करें", "Send voice message": "आवाज़ का संदेश भेजें", "Stop listening": "सुनना बंद करें", "Stop": "रोकें",
  "Banking proposal": "बैंकिंग प्रस्ताव", "Please confirm": "कृपया पुष्टि करें", "Confirmation expired": "पुष्टि का समय समाप्त", "Between your accounts": "आपके खातों के बीच", "Bill payment": "बिल भुगतान", "Card controls": "कार्ड नियंत्रण", "Card payment": "कार्ड भुगतान", "Cancel direct debit": "ऑटो डेबिट रद्द करें", "Transfer": "ट्रांसफ़र",
  "Confirm transfer": "ट्रांसफ़र की पुष्टि करें", "Confirm payment": "भुगतान की पुष्टि करें", "Confirm cancellation": "रद्द करने की पुष्टि करें", "Confirm card change": "कार्ड बदलाव की पुष्टि करें", "Processing…": "प्रक्रिया जारी है…", "From": "इस खाते से", "To": "इस खाते में", "Amount": "राशि", "Reference": "संदर्भ", "Payment method": "भुगतान का तरीका", "Fees": "शुल्क", "Not provided by the bank": "बैंक ने जानकारी नहीं दी", "Completion": "पूरा होने का समय", "On confirmation": "पुष्टि के बाद",
  "Earlier step": "पिछला चरण", "Payment review": "भुगतान की समीक्षा", "Transfer between accounts": "खातों के बीच ट्रांसफ़र", "Confirm by": "इस समय तक पुष्टि करें", "View receipt ↗": "रसीद देखें ↗", "View transaction ↗": "लेन-देन देखें ↗", "Open banking details ↗": "बैंकिंग विवरण खोलें ↗",
  "This proposal requires a newer version of Nexa.": "इस प्रस्ताव के लिए Nexa का नया संस्करण चाहिए।", "This banking summary needs a newer version of Nexa.": "इस बैंकिंग सारांश के लिए Nexa का नया संस्करण चाहिए।",
  "Spending summary": "खर्च का सारांश", "Category breakdown": "श्रेणी के अनुसार खर्च", "Total spending": "कुल खर्च", "No spending in this period.": "इस अवधि में कोई खर्च नहीं है।", "Previous-period comparison is not available.": "पिछली अवधि से तुलना उपलब्ध नहीं है।", "Explore transaction history ↗": "लेन-देन का इतिहास देखें ↗", "Original summary": "मूल सारांश",
  "Loading your banking information": "आपकी बैंकिंग जानकारी लोड हो रही है", "Please wait a moment.": "कृपया थोड़ा इंतज़ार करें।", "We couldn’t load this information": "यह जानकारी लोड नहीं हो सकी", "Information will appear here when it’s available.": "जानकारी उपलब्ध होने पर यहाँ दिखाई देगी।", "Close dialog": "डायलॉग बंद करें", "Close ×": "बंद करें ×",
  "Recent transactions": "हाल के लेन-देन", "Transaction details": "लेन-देन का विवरण", "Loading transactions…": "लेन-देन लोड हो रहे हैं…", "Transactions couldn’t be loaded. Please try again.": "लेन-देन लोड नहीं हो सके। फिर कोशिश करें।", "No transactions to show.": "दिखाने के लिए कोई लेन-देन नहीं है।", "Retry": "फिर कोशिश करें", "Previous": "पिछला", "Next": "अगला", "View all transactions": "सभी लेन-देन देखें",
  "Account": "खाता", "Date & time": "दिनांक और समय", "Category": "श्रेणी", "Type": "प्रकार", "Status": "स्थिति", "Recipient": "प्राप्तकर्ता", "Back to transactions": "लेन-देन पर वापस जाएँ", "← Back to balances": "← बैलेंस पर वापस जाएँ",
  "AutoPay mandates": "ऑटोपे निर्देश", "Your beneficiaries": "आपके प्राप्तकर्ता", "Your cards": "आपके कार्ड", "Your loans": "आपके ऋण", "Your bills": "आपके बिल", "Upcoming payments": "आगामी भुगतान", "Outstanding": "बकाया", "Available limit": "उपलब्ध सीमा", "Payment due": "भुगतान की तारीख", "Debit card": "डेबिट कार्ड", "Frequency": "आवृत्ति", "Next debit": "अगला डेबिट", "Not scheduled": "तय नहीं है", "Up to": "अधिकतम", "Next EMI": "अगली ईएमआई", "Due": "देय", "No due date": "देय तारीख नहीं है", "Customer": "ग्राहक",
  "No accounts to show.": "दिखाने के लिए कोई खाता नहीं है।", "No cards to show.": "दिखाने के लिए कोई कार्ड नहीं है।", "No bills to show.": "दिखाने के लिए कोई बिल नहीं है।", "No loans to show.": "दिखाने के लिए कोई ऋण नहीं है।", "No mandates to show.": "कोई ऑटोपे निर्देश नहीं है।", "No saved beneficiaries.": "कोई सहेजा गया प्राप्तकर्ता नहीं है।", "No scheduled payments.": "कोई निर्धारित भुगतान नहीं है।", "No records to show.": "कोई रिकॉर्ड नहीं है।",
  "Today": "आज", "Yesterday": "कल", "Due today": "आज देय", "Due tomorrow": "कल देय", "Date unavailable": "तारीख उपलब्ध नहीं है", "Amount unavailable": "राशि उपलब्ध नहीं है", "Number unavailable": "नंबर उपलब्ध नहीं है",
  "Completed": "पूरा हुआ", "Active": "सक्रिय", "Paid": "भुगतान हुआ", "Failed": "विफल", "Pending": "लंबित", "Overdue": "अतिदेय", "Blocked": "अवरुद्ध", "Cancelled": "रद्द", "Frozen": "बंद", "Details checked": "विवरण जाँचे गए", "Awaiting verification": "सत्यापन की प्रतीक्षा", "Not completed": "पूरा नहीं हुआ", "No money moved": "पैसे नहीं भेजे गए", "Received": "प्राप्त", "Incoming": "आने वाला", "Spent": "खर्च", "Outgoing": "जाने वाला",
  "item": "आइटम", "items": "आइटम", "Scroll across to browse": "और देखने के लिए स्क्रॉल करें", "Scroll for more": "और देखने के लिए स्क्रॉल करें", "Navigation": "नेविगेशन", "Chat": "बातचीत", "Overview": "सारांश", "Send money": "पैसे भेजें", "Payees": "प्राप्तकर्ता", "Direct debits": "ऑटो डेबिट", "Scheduled payments": "निर्धारित भुगतान", "Loans": "ऋण", "Profile & settings": "प्रोफ़ाइल और सेटिंग्स", "Security & session": "सुरक्षा और सत्र", "Ask Nexa": "Nexa से पूछें", "Skip to conversation": "बातचीत पर जाएँ"
};
Object.assign(hindi, {
  "Hi! How can I help with your banking today?": "नमस्ते! आज आपकी बैंकिंग में कैसे मदद करूँ?",
  "Discard your typed message and continue?": "अपना लिखा हुआ संदेश हटाकर आगे बढ़ें?",
  "This request could not be completed. Review the proposal or cancel it to start again.": "अनुरोध पूरा नहीं हो सका। प्रस्ताव जाँचें या रद्द करके फिर शुरू करें।",
  "Chat is temporarily unavailable. Please try again shortly.": "बातचीत अभी उपलब्ध नहीं है। थोड़ी देर बाद फिर कोशिश करें।",
  "I could not load your conversations. Please reload the page to try again.": "बातचीत लोड नहीं हो सकी। पेज फिर लोड करें।",
  "This conversation couldn’t be opened. Please try again.": "यह बातचीत नहीं खुल सकी। फिर कोशिश करें।",
  "Earlier messages couldn’t be loaded. Please try again.": "पुराने संदेश लोड नहीं हो सके। फिर कोशिश करें।",
  "History couldn’t be loaded. Please try again.": "इतिहास लोड नहीं हो सका। फिर कोशिश करें।",
  "Your session has expired. Sign in again to continue.": "आपका सत्र समाप्त हो गया है। जारी रखने के लिए फिर साइन इन करें।",
  "We could not check whether your message arrived. Choose Try again. We will check the same message without adding it twice.": "संदेश पहुँचा या नहीं, इसकी पुष्टि नहीं हो सकी। फिर कोशिश करें चुनें। उसी संदेश को दोहराए बिना जाँच की जाएगी।",
  "Voice input is unavailable in this browser. You can still type your message.": "इस ब्राउज़र में आवाज़ से पूछना उपलब्ध नहीं है। आप संदेश लिख सकते हैं।",
  "Microphone access is off. Allow it in your browser to speak, or type your message.": "माइक्रोफ़ोन की अनुमति बंद है। बोलने के लिए ब्राउज़र में अनुमति दें या संदेश लिखें।",
  "I couldn’t hear that clearly. Please try again or type your message.": "आवाज़ साफ़ नहीं सुनाई दी। फिर कोशिश करें या संदेश लिखें।",
  "The microphone couldn’t start. Please try again or type your message.": "माइक्रोफ़ोन शुरू नहीं हुआ। फिर कोशिश करें या संदेश लिखें।",
  "No speech was captured. Please try again.": "आवाज़ दर्ज नहीं हुई। फिर कोशिश करें।",
  "That voice message is too long. Please try a shorter message.": "आवाज़ का संदेश बहुत लंबा है। छोटा संदेश बोलें।",
  "Follow-up suggestions": "आगे पूछें", "Review a bill payment": "बिल भुगतान जाँचें",
  "Savings": "बचत", "Current": "चालू", "Transaction type": "लेन-देन का प्रकार", "Transaction reference": "लेन-देन का संदर्भ", "Copy reference": "संदर्भ कॉपी करें", "Reference copied.": "संदर्भ कॉपी किया गया।", "Need help with this transaction?": "इस लेन-देन के लिए मदद चाहिए?", "← Back to transactions": "← लेन-देन पर वापस जाएँ", "Received in": "इस खाते में प्राप्त", "Paid from": "इस खाते से भुगतान", "View details": "विवरण देखें",
  "Payment details": "भुगतान का विवरण", "Source": "स्रोत", "Target": "प्राप्तकर्ता", "Action": "कार्रवाई", "Transfer status": "ट्रांसफ़र की स्थिति", "Ask another banking question to continue.": "आगे बढ़ने के लिए बैंकिंग का एक और सवाल पूछें।", "Banking information could not be retrieved.": "बैंकिंग जानकारी नहीं मिल सकी।",
  "Transaction pages": "लेन-देन के पेज", "Page": "पेज", "of": "में से", "navigation": "नेविगेशन", "failed": "विफल", "overdue": "अतिदेय", "need attention": "ध्यान दें", "pending": "लंबित", "awaiting verification": "सत्यापन की प्रतीक्षा", "blocked": "अवरुद्ध",
  "Back to sign in": "साइन इन पर वापस जाएँ", "PERSONAL BANKING": "व्यक्तिगत बैंकिंग", "Welcome to Nexa": "Nexa में आपका स्वागत है", "Join Nexa": "Nexa से जुड़ें", "Authentication options": "साइन इन के विकल्प", "Log in": "लॉग इन", "Create account": "खाता बनाएँ", "Existing customer": "मौजूदा ग्राहक", "New customer": "नए ग्राहक", "Log in to Nexa": "Nexa में लॉग इन करें", "Create your account": "अपना खाता बनाएँ",
  "Check your balance, view payments or ask for help. You can type or speak.": "बैलेंस जाँचें, भुगतान देखें या मदद माँगें। लिखकर या बोलकर पूछ सकते हैं।",
  "Enter your details to get started. You can open a bank account after signing up.": "शुरू करने के लिए अपना विवरण भरें। साइन अप करने के बाद बैंक खाता खोल सकते हैं।",
  "Full name": "पूरा नाम", "Your full name": "आपका पूरा नाम", "Email address": "ईमेल पता", "Phone number": "फ़ोन नंबर", "Optional": "वैकल्पिक", "Password": "पासवर्ड", "Enter your password": "अपना पासवर्ड लिखें", "Hide password": "पासवर्ड छिपाएँ", "Show password": "पासवर्ड दिखाएँ", "Hide": "छिपाएँ", "Show": "दिखाएँ", "Sign in to Nexa": "Nexa में साइन इन करें", "Signing you in…": "साइन इन हो रहा है…", "Creating your account…": "आपका खाता बनाया जा रहा है…",
  "Use 8–72 characters. Include a capital letter (A), a small letter (a), a number (1) and a symbol (!).": "8–72 अक्षर रखें। एक बड़ा अक्षर (A), छोटा अक्षर (a), अंक (1) और चिह्न (!) शामिल करें।",
  "Enter your email address, for example name@example.com.": "अपना ईमेल पता लिखें, जैसे name@example.com।", "Enter your password using 8–72 characters.": "8–72 अक्षरों का पासवर्ड लिखें।", "Include uppercase, lowercase, a number, and a special character in your password.": "पासवर्ड में बड़ा अक्षर, छोटा अक्षर, अंक और विशेष चिह्न शामिल करें।", "Enter your full name.": "अपना पूरा नाम लिखें।",
  "Your email or password doesn’t match. Check both and try again.": "ईमेल या पासवर्ड मेल नहीं खाता। दोनों जाँचकर फिर कोशिश करें।", "We couldn’t sign you in. Check your details and try again.": "साइन इन नहीं हो सका। विवरण जाँचकर फिर कोशिश करें।",
  "Transfer Indian rupees to another Nexa account.": "दूसरे Nexa खाते में भारतीय रुपये भेजें।", "Transfer details": "ट्रांसफ़र का विवरण", "From account": "इस खाते से", "To account": "इस खाते में", "Choose an account": "खाता चुनें", "Choose another account": "दूसरा खाता चुनें", "Who are you sending to?": "किसे पैसे भेज रहे हैं?", "Another Nexa account": "दूसरा Nexa खाता", "One of my Nexa accounts": "मेरे Nexa खातों में से एक", "Recipient’s Nexa account number": "प्राप्तकर्ता का Nexa खाता नंबर", "Amount (₹)": "राशि (₹)", "For example, 500": "उदाहरण के लिए, 500", "Review transfer": "ट्रांसफ़र जाँचें", "Checking recipient…": "प्राप्तकर्ता की जाँच हो रही है…",
  "Ask the recipient for their full account number. You’ll see their name before sending.": "प्राप्तकर्ता से पूरा खाता नंबर लें। भेजने से पहले उनका नाम दिखाई देगा।", "This is more than your available balance.": "यह आपके उपलब्ध बैलेंस से अधिक है।", "Enter an amount above ₹0, with up to two decimal places.": "₹0 से अधिक राशि लिखें, दशमलव के बाद अधिकतम दो अंक रखें।", "Transfers are currently available between Nexa accounts. Other-bank and UPI transfers are not supported.": "अभी केवल Nexa खातों के बीच ट्रांसफ़र उपलब्ध है। दूसरे बैंकों और UPI में ट्रांसफ़र उपलब्ध नहीं है।",
  "Check before you send": "भेजने से पहले जाँचें", "To Nexa account": "Nexa खाते में", "✓ Money sent": "✓ पैसे भेजे गए", "This review has expired": "इस समीक्षा का समय समाप्त हो गया", "Edit details": "विवरण बदलें", "Please wait…": "कृपया इंतज़ार करें…", "Check transfer status": "ट्रांसफ़र की स्थिति जाँचें", "View transaction": "लेन-देन देखें", "Make another transfer": "एक और ट्रांसफ़र करें", "Start a new review": "नई समीक्षा शुरू करें",
  "Check the recipient and amount carefully. Sending moves money immediately. This review is valid for 5 minutes.": "प्राप्तकर्ता और राशि ध्यान से जाँचें। भेजने पर पैसे तुरंत स्थानांतरित होंगे। यह समीक्षा 5 मिनट तक मान्य है।", "Your transfer is complete. The money has been added to the recipient’s Nexa account.": "आपका ट्रांसफ़र पूरा हो गया। प्राप्तकर्ता के Nexa खाते में पैसे जोड़ दिए गए हैं।"
});
Object.assign(hindi, {
  "Your accounts, activity and next steps. All in one place.": "आपके खाते, गतिविधि और अगले कदम, सब एक जगह।", "＋ Open an account": "＋ खाता खोलें", "＋ Open account": "＋ खाता खोलें", "TOTAL AVAILABLE BALANCE": "कुल उपलब्ध बैलेंस", "Connected accounts": "जुड़े हुए खाते", "Across": "इन खातों में", "View accounts": "खाते देखें", "Send money →": "पैसे भेजें →", "BANKING, MADE SIMPLE": "बैंकिंग, अब आसान", "Start with a conversation.": "बातचीत से शुरू करें।", "Type or speak to check your balance, see recent payments, or get help. English and Hindi voice available.": "बैलेंस जाँचने, हाल के भुगतान देखने या मदद के लिए लिखें या बोलें। हिन्दी और अंग्रेज़ी में बोल सकते हैं।",
  "View all accounts ↗": "सभी खाते देखें ↗", "Your first account starts here": "आपका पहला खाता यहाँ से शुरू होता है", "Open a bank account": "बैंक खाता खोलें", "Recent activity": "हाल की गतिविधि", "View history ↗": "इतिहास देखें ↗", "Activity at a glance": "गतिविधि एक नज़र में", "Completed activity in the latest": "हाल के पूर्ण हुए", "transactions for this account.": "इस खाते के लेन-देन।", "Money in": "आए पैसे", "Money out": "गए पैसे", "Bills and due dates": "बिल और देय तारीखें", "Session and security": "सत्र और सुरक्षा",
  "A clear view of every account you hold with Nexa.": "Nexa में आपके हर खाते की साफ़ जानकारी।", "Account information": "खाते की जानकारी", "Account name": "खाते का नाम", "Account number": "खाता नंबर", "Ledger balance": "लेजर बैलेंस", "Last updated": "आखिरी अपडेट", "No bank accounts yet": "अभी कोई बैंक खाता नहीं है", "has been opened.": "खोल दिया गया है।", "available": "उपलब्ध", "Done": "पूरा हुआ", "Account type": "खाते का प्रकार", "Date of birth": "जन्म तिथि", "Address": "पता", "Opening balance": "शुरुआती बैलेंस", "Currency": "मुद्रा", "Your account starts with a zero balance. Please confirm the details before opening.": "आपका खाता शून्य बैलेंस से शुरू होगा। खोलने से पहले विवरण की पुष्टि करें।", "Complete your customer details to open a zero-balance account.": "शून्य बैलेंस खाता खोलने के लिए अपना विवरण भरें।", "e.g. Everyday savings": "जैसे, रोज़मर्रा की बचत", "Review account": "खाता जाँचें",
  "Search": "खोजें", "Merchant or reference": "व्यापारी या संदर्भ", "Direction": "पैसों की दिशा", "All activity": "सभी गतिविधियाँ", "Any category": "कोई भी श्रेणी", "Apply filters": "फ़िल्टर लगाएँ", "Reset": "रीसेट", "Date and time": "दिनांक और समय", "Back to history": "इतिहास पर वापस जाएँ", "· Page": "· पेज", "← Previous": "← पिछला", "Next →": "अगला →", "Review a payment": "भुगतान जाँचें", "What would you like to review?": "आप क्या जाँचना चाहते हैं?", "Transfer to a payee": "प्राप्तकर्ता को ट्रांसफ़र", "Credit card payment": "क्रेडिट कार्ड भुगतान", "Cancel a direct debit": "ऑटो डेबिट रद्द करें", "Select an account": "खाता चुनें", "Select a record": "रिकॉर्ड चुनें", "There is nothing to choose here yet. Contact your bank if you expected to see an item.": "अभी चुनने के लिए कुछ नहीं है। कोई रिकॉर्ड गायब हो तो अपने बैंक से संपर्क करें।", "Records page": "रिकॉर्ड का पेज", "Previous records": "पिछले रिकॉर्ड", "Next records": "अगले रिकॉर्ड", "Amount (INR)": "राशि (INR)", "Enter an amount above ₹0, for example 100 or 100.50.": "₹0 से अधिक राशि लिखें, जैसे 100 या 100.50।", "Check these details": "ये विवरण जाँचें", "View saved payees ↗": "सहेजे हुए प्राप्तकर्ता देखें ↗", "View scheduled payments ↗": "निर्धारित भुगतान देखें ↗", "Continue": "जारी रखें", "Back to payments": "भुगतान पर वापस जाएँ",
  "Banking operations": "बैंकिंग कार्य", "Post a deposit, withdrawal or internal account transfer.": "जमा, निकासी या आंतरिक खाते का ट्रांसफ़र दर्ज करें।", "These actions move account balances immediately. Verify the account details and amount before confirming.": "इन कार्रवाइयों से बैलेंस तुरंत बदलता है। पुष्टि से पहले खाते और राशि की जाँच करें।", "New transaction": "नया लेन-देन", "Operation": "कार्रवाई", "Internal transfer": "आंतरिक ट्रांसफ़र", "Deposit": "जमा", "Withdrawal": "निकासी", "Source account": "स्रोत खाता", "Select account": "खाता चुनें", "Destination account": "प्राप्तकर्ता खाता", "Review transaction": "लेन-देन जाँचें", "The last result is not confirmed. Check the transaction history before starting another transaction.": "पिछले नतीजे की पुष्टि नहीं हुई है। दूसरा लेन-देन करने से पहले इतिहास जाँचें।", "Reference:": "संदर्भ:", "Your bank has confirmed this transaction.": "बैंक ने इस लेन-देन की पुष्टि की है।", "This action posts immediately. Only confirm if these details are correct.": "यह कार्रवाई तुरंत दर्ज होती है। विवरण सही होने पर ही पुष्टि करें।", "Do not resubmit. Check the account’s transaction history with your bank before attempting another transaction.": "दोबारा न भेजें। दूसरा लेन-देन करने से पहले बैंक से खाते का इतिहास जाँचें।",
  "Find on this page": "इस पेज पर खोजें", "All statuses": "सभी स्थितियाँ", "← Back to": "← वापस जाएँ", "Details": "विवरण", "Bank": "बैंक", "Card type": "कार्ड का प्रकार", "Credit limit": "क्रेडिट सीमा", "Minimum payment": "न्यूनतम भुगतान", "Due date": "देय तारीख", "Interest rate": "ब्याज दर", "Next instalment": "अगली किस्त", "Linked account": "जुड़ा हुआ खाता", "View account ↗": "खाता देखें ↗", "Payment history": "भुगतान का इतिहास", "Card activity": "कार्ड की गतिविधि",
  "Checking your previous transfer": "पिछले ट्रांसफ़र की जाँच हो रही है", "We’ll check the saved request before you send money again.": "दोबारा पैसे भेजने से पहले सहेजे हुए अनुरोध की जाँच होगी।", "No money was sent by this request. Review the details again to create a new transfer.": "इस अनुरोध से पैसे नहीं भेजे गए। नया ट्रांसफ़र बनाने के लिए विवरण फिर जाँचें।", "Available:": "उपलब्ध:", "You need two active INR accounts for this option.": "इस विकल्प के लिए दो सक्रिय INR खाते चाहिए।", "Review bills and other payments →": "बिल और अन्य भुगतान जाँचें →",
  "Keep your personal banking details up to date.": "अपने बैंकिंग विवरण को अपडेट रखें।", "Understand and manage your current sign-in.": "अपने वर्तमान साइन इन की जानकारी देखें और प्रबंधित करें।", "Your current session": "आपका वर्तमान सत्र", "Signed in to Nexa": "Nexa में साइन इन है", "Email": "ईमेल", "Account status": "खाते की स्थिति", "Access": "पहुँच", "Sign out when you finish banking, especially on a shared phone or computer.": "बैंकिंग पूरी होने पर साइन आउट करें, खासकर साझा फ़ोन या कंप्यूटर पर।", "Sign out of this session": "इस सत्र से साइन आउट करें", "Keep your banking private": "अपनी बैंकिंग निजी रखें", "Never share your password or sign-in details. Always sign out on a shared device.": "पासवर्ड या साइन इन विवरण साझा न करें। साझा डिवाइस पर हमेशा साइन आउट करें।", "Online password changes, multi-factor authentication controls, device management and security alerts are not available in this application. Contact your bank for help with these services.": "इस ऐप में ऑनलाइन पासवर्ड बदलना, बहु-स्तरीय सत्यापन, डिवाइस प्रबंधन और सुरक्षा अलर्ट उपलब्ध नहीं हैं। इन सेवाओं के लिए बैंक से संपर्क करें।", "This page is not available for your session.": "यह पेज आपके सत्र के लिए उपलब्ध नहीं है।", "Back to overview": "सारांश पर वापस जाएँ", "Nexa chat": "Nexa बातचीत", "Main navigation": "मुख्य नेविगेशन", "Skip to main content": "मुख्य सामग्री पर जाएँ", "Open navigation": "नेविगेशन खोलें", "☰ Menu": "☰ मेन्यू", "Ask Nexa — type or speak for help": "Nexa से पूछें — मदद के लिए लिखें या बोलें", "✧ Ask Nexa": "✧ Nexa से पूछें", "Your everyday banking, connected.": "आपकी रोज़मर्रा की बैंकिंग, एक साथ।", "Security & session ↗": "सुरक्षा और सत्र ↗", "Quick navigation": "आसान नेविगेशन", "More": "और",
  "Your Nexa profile": "आपकी Nexa प्रोफ़ाइल", "Account settings": "खाते की सेटिंग्स", "Check or change your personal details.": "अपना व्यक्तिगत विवरण जाँचें या बदलें।", "Personal information": "व्यक्तिगत जानकारी", "Your name, address and phone number are stored with your customer profile.": "आपका नाम, पता और फ़ोन नंबर ग्राहक प्रोफ़ाइल में सहेजे जाते हैं।", "Login email": "लॉग इन ईमेल", "Nexa bank account": "Nexa बैंक खाता", "Live account information from your Nexa banking record.": "आपके Nexa बैंकिंग रिकॉर्ड से खाते की जानकारी।", "ACCOUNT": "खाता", "No Nexa account yet": "अभी Nexa खाता नहीं है", "Open an account from Accounts to see its balance and details here.": "यहाँ बैलेंस और विवरण देखने के लिए खाते सेक्शन में खाता खोलें।", "Session": "सत्र", "Sign out securely when you have finished using Nexa.": "Nexa का इस्तेमाल पूरा होने पर सुरक्षित रूप से साइन आउट करें।", "Signed in as": "इस रूप में साइन इन है"
});
Object.assign(hindi, { "More Banking": "और बैंकिंग सेवाएँ", "More banking": "और बैंकिंग सेवाएँ", "Banking navigation": "बैंकिंग नेविगेशन", "Banking navigation and history": "बैंकिंग नेविगेशन और बातचीत का इतिहास" });
Object.assign(hindi, {
  "Your conversation": "आपकी बातचीत", "Your money.": "आपका पैसा।", "Your conversation.": "आपकी बातचीत।",
  "A LITTLE MORE HUMAN.": "बैंकिंग, आपके करीब।", "A little more human.": "बैंकिंग, आपके करीब।",
  "A question, a plan, a little peace of mind.": "एक सवाल, एक योजना, थोड़ी निश्चिंतता।",
  "Whatever’s on your mind, start here.": "जो भी पूछना चाहें, यहाँ से शुरू करें।", "Here for you": "आपकी मदद के लिए",
  "Search conversations": "बातचीत खोजें", "No matching conversations.": "कोई मिलती-जुलती बातचीत नहीं मिली।",
  "Back to home": "होम पर वापस जाएँ", "Welcome back": "फिर से स्वागत है", "Your space.": "आपकी जगह।",
  "A new beginning.": "एक नई शुरुआत।", "One hello away.": "बस एक नमस्ते की दूरी पर।",
  "Log in to continue your conversation with Nexa.": "Nexa से बातचीत जारी रखने के लिए लॉग इन करें।",
  "Start with the basics. Your next chapter starts here.": "अपनी जानकारी भरें। आपकी नई शुरुआत यहीं से होती है।",
  "Phone number (optional)": "फ़ोन नंबर (वैकल्पिक)", "New to Nexa?": "Nexa पर नए हैं?",
  "Already have an account?": "पहले से खाता है?", "Create an account": "खाता बनाएँ",
  "Your money. Your words. Your way.": "आपका पैसा। आपके शब्द। आपका तरीका।", "Nexa workspace": "Nexa कार्यक्षेत्र"
});
Object.assign(hindi, {
  "Transaction": "लेन-देन", "Amount / status": "राशि / स्थिति", "Latest": "नवीनतम", "transaction": "लेन-देन", "transactions": "लेन-देन",
  "More filters": "और फ़िल्टर", "active": "लागू",
  "Spending by category": "श्रेणी के अनुसार खर्च", "Share of money out": "कुल खर्च में हिस्सा", "Uncategorized": "बिना श्रेणी", "Other categories": "अन्य श्रेणियाँ",
  "Completed transactions only. Pending and failed payments are excluded.": "केवल पूरे हुए लेन-देन। लंबित और असफल भुगतान शामिल नहीं हैं।",
  "No completed spending in these transactions.": "इन लेन-देन में कोई खर्च पूरा नहीं हुआ है।",
  "Choose an account to see its activity.": "गतिविधि देखने के लिए खाता चुनें।",
  "This activity summary is unavailable. View transaction history for details.": "गतिविधि का सार उपलब्ध नहीं है। विवरण के लिए लेन-देन का इतिहास देखें।"
});
Object.assign(hindi, {
  "How can I help?": "मैं कैसे मदद कर सकता हूँ?", "Transfer between accounts": "खातों के बीच पैसे भेजें",
  "Speech recognition may use your browser’s speech service.": "वाक् पहचान आपके ब्राउज़र की स्पीच सेवा का उपयोग कर सकती है।"
});
Object.assign(hindi, {
  "Spoken replies are on. Say ‘stop reading’ to turn them off.": "अब जवाब हिन्दी में सुनाए जाएँगे। बंद करने के लिए ‘जवाब सुनाना बंद करें’ चुनें।",
  "Spoken replies are off.": "जवाब सुनाना बंद है।"
});
Object.assign(hindi, { "account": "खाता" });
export function t(text: string, language: Locale = locale): string { return language === "hi-IN" && Object.prototype.hasOwnProperty.call(hindi, text) ? hindi[text] : text; }
