-- Preserve the original financial records for audit; no runtime code reads these archives.
-- Preflight before Oracle DDL (which auto-commits): unsupported monetary values require reconciliation.
DECLARE
  invalid_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO invalid_count FROM bank_accounts
   WHERE account_type NOT IN ('SAVINGS','CURRENT') OR currency_code <> 'INR'
      OR available_balance <> ledger_balance OR ledger_balance <> ROUND(ledger_balance,2);
  IF invalid_count > 0 THEN RAISE_APPLICATION_ERROR(-20001, 'Reconcile unsupported account types, currencies, holds or fractional paise before the banking merge.'); END IF;
  SELECT COUNT(*) INTO invalid_count FROM users WHERE phone_number IN (SELECT phone_number FROM users WHERE phone_number IS NOT NULL GROUP BY phone_number HAVING COUNT(*)>1);
  IF invalid_count > 0 THEN RAISE_APPLICATION_ERROR(-20003, 'Resolve duplicate customer phone numbers before the banking merge.'); END IF;
  SELECT COUNT(*) INTO invalid_count FROM transactions WHERE amount = 0 OR amount <> ROUND(amount,2) OR status = 'PENDING';
  IF invalid_count > 0 THEN RAISE_APPLICATION_ERROR(-20002, 'Reconcile zero, fractional-paise or pending transactions before the banking merge.'); END IF;
END;
/
ALTER TABLE bank_accounts RENAME TO legacy_bank_accounts;
ALTER TABLE transactions RENAME TO legacy_transactions;
ALTER TABLE journal_entries RENAME TO legacy_journal_entries;
ALTER TABLE ledger_accounts RENAME TO legacy_ledger_accounts;
ALTER TABLE ledger_postings RENAME TO legacy_ledger_postings;

CREATE TABLE CUSTOMERS (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USER_ID VARCHAR2(26) UNIQUE REFERENCES USERS(ID),
    FULL_NAME VARCHAR2(160) NOT NULL,
    EMAIL VARCHAR2(254) NOT NULL UNIQUE,
    PHONE_NUMBER VARCHAR2(32) UNIQUE,
    DATE_OF_BIRTH DATE,
    ADDRESS VARCHAR2(255),
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL
);

CREATE TABLE ACCOUNTS (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ACCOUNT_NUMBER VARCHAR2(30) NOT NULL UNIQUE,
    CUSTOMER_ID NUMBER,
    ACCOUNT_NAME VARCHAR2(120) NOT NULL,
    ACCOUNT_TYPE VARCHAR2(20) NOT NULL,
    ACCOUNT_CATEGORY VARCHAR2(20) NOT NULL,
    CURRENCY_CODE VARCHAR2(3) DEFAULT 'INR' NOT NULL,
    VERSION NUMBER(19) DEFAULT 0 NOT NULL,
    BALANCE NUMBER(19,2) DEFAULT 0 NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT FK_ACCOUNTS_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID),
    CONSTRAINT CK_ACCOUNTS_TYPE CHECK (ACCOUNT_TYPE IN ('SAVINGS','CURRENT','CASH','CLEARING')),
    CONSTRAINT CK_ACCOUNTS_CATEGORY CHECK (ACCOUNT_CATEGORY IN ('CUSTOMER','SYSTEM')),
    CONSTRAINT CK_ACCOUNTS_STATUS CHECK (STATUS IN ('ACTIVE','BLOCKED','CLOSED')),
    CONSTRAINT CK_SYSTEM_ACCOUNT_CUSTOMER CHECK ((ACCOUNT_CATEGORY = 'SYSTEM' AND CUSTOMER_ID IS NULL) OR (ACCOUNT_CATEGORY = 'CUSTOMER' AND CUSTOMER_ID IS NOT NULL))
);

CREATE TABLE TRANSACTIONS (
    ID VARCHAR2(40) PRIMARY KEY,
    TRANSACTION_TYPE VARCHAR2(20) NOT NULL,
    SOURCE_ACCOUNT_ID NUMBER,
    DESTINATION_ACCOUNT_ID NUMBER,
    MERCHANT_NAME VARCHAR2(200),
    CATEGORY VARCHAR2(80),
    PAYMENT_METHOD VARCHAR2(32),
    AMOUNT NUMBER(19,2) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    COMPLETED_AT TIMESTAMP,
    CONSTRAINT FK_TX_SOURCE FOREIGN KEY (SOURCE_ACCOUNT_ID) REFERENCES ACCOUNTS(ID),
    CONSTRAINT FK_TX_DESTINATION FOREIGN KEY (DESTINATION_ACCOUNT_ID) REFERENCES ACCOUNTS(ID),
    CONSTRAINT CK_TX_TYPE CHECK (TRANSACTION_TYPE IN ('DEPOSIT','WITHDRAWAL','TRANSFER')),
    CONSTRAINT CK_TX_AMOUNT CHECK (AMOUNT > 0),
    CONSTRAINT CK_TX_STATUS CHECK (STATUS IN ('SUCCESS','FAILED','REVERSED')),
    CONSTRAINT CK_TX_ACCOUNTS CHECK ((TRANSACTION_TYPE='DEPOSIT' AND SOURCE_ACCOUNT_ID IS NULL AND DESTINATION_ACCOUNT_ID IS NOT NULL) OR (TRANSACTION_TYPE='WITHDRAWAL' AND SOURCE_ACCOUNT_ID IS NOT NULL AND DESTINATION_ACCOUNT_ID IS NULL) OR (TRANSACTION_TYPE='TRANSFER' AND SOURCE_ACCOUNT_ID IS NOT NULL AND DESTINATION_ACCOUNT_ID IS NOT NULL))
);

CREATE TABLE JOURNAL_ENTRIES (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TRANSACTION_ID VARCHAR2(40) NOT NULL UNIQUE,
    ENTRY_REFERENCE VARCHAR2(40) NOT NULL UNIQUE,
    ENTRY_TYPE VARCHAR2(20) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT FK_JOURNAL_TRANSACTION FOREIGN KEY (TRANSACTION_ID) REFERENCES TRANSACTIONS(ID),
    CONSTRAINT CK_JOURNAL_TYPE CHECK (ENTRY_TYPE IN ('TRANSACTION','REVERSAL')),
    CONSTRAINT CK_JOURNAL_STATUS CHECK (STATUS IN ('POSTED','REVERSED'))
);

CREATE TABLE LEDGER_ENTRIES (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    JOURNAL_ENTRY_ID NUMBER NOT NULL,
    ACCOUNT_ID NUMBER NOT NULL,
    ENTRY_TYPE VARCHAR2(10) NOT NULL,
    AMOUNT NUMBER(19,2) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT FK_LEDGER_JOURNAL FOREIGN KEY (JOURNAL_ENTRY_ID) REFERENCES JOURNAL_ENTRIES(ID),
    CONSTRAINT FK_LEDGER_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS(ID),
    CONSTRAINT CK_LEDGER_TYPE CHECK (ENTRY_TYPE IN ('DEBIT','CREDIT')),
    CONSTRAINT CK_LEDGER_AMOUNT CHECK (AMOUNT > 0)
);

CREATE INDEX IDX_ACCOUNTS_CUSTOMER ON ACCOUNTS(CUSTOMER_ID);
CREATE INDEX IDX_TX_SOURCE ON TRANSACTIONS(SOURCE_ACCOUNT_ID);
CREATE INDEX IDX_TX_DESTINATION ON TRANSACTIONS(DESTINATION_ACCOUNT_ID);
CREATE INDEX IDX_LEDGER_ACCOUNT ON LEDGER_ENTRIES(ACCOUNT_ID);
CREATE INDEX IDX_LEDGER_JOURNAL ON LEDGER_ENTRIES(JOURNAL_ENTRY_ID);

INSERT INTO customers (user_id,full_name,email,phone_number,created_at,updated_at)
SELECT id,full_name,email,phone_number,SYS_EXTRACT_UTC(created_at),SYS_EXTRACT_UTC(updated_at) FROM users WHERE role='CUSTOMER' OR id IN (SELECT user_id FROM legacy_bank_accounts);
CREATE TABLE banking_account_migration (legacy_id VARCHAR2(26) PRIMARY KEY, account_id NUMBER NOT NULL UNIQUE REFERENCES accounts(id));
INSERT INTO accounts (account_number,customer_id,account_name,account_type,account_category,balance,status,currency_code,created_at,updated_at)
SELECT a.account_number,c.id,a.display_name,a.account_type,'CUSTOMER',a.ledger_balance,
CASE a.status WHEN 'FROZEN' THEN 'BLOCKED' ELSE a.status END,a.currency_code,SYS_EXTRACT_UTC(a.created_at),SYS_EXTRACT_UTC(a.updated_at)
FROM legacy_bank_accounts a JOIN customers c ON c.user_id=a.user_id;
INSERT INTO banking_account_migration (legacy_id,account_id)
SELECT old.id,a.id FROM legacy_bank_accounts old JOIN accounts a ON a.account_number=old.account_number;
-- The cash account starts at the reconciled customer total; this is a cutover balance, not a new deposit.
INSERT INTO accounts (account_number,account_name,account_type,account_category,balance,status,created_at,updated_at)
SELECT 'SYSTEM-CASH','System cash account','CASH','SYSTEM',COALESCE(SUM(balance),0),'ACTIVE',SYS_EXTRACT_UTC(SYSTIMESTAMP),SYS_EXTRACT_UTC(SYSTIMESTAMP) FROM accounts;
-- Import history without replaying balances or inventing missing historical journal postings.
INSERT INTO transactions (id,transaction_type,source_account_id,destination_account_id,amount,status,created_at,completed_at,merchant_name,category,payment_method)
SELECT t.id,CASE WHEN t.amount>0 THEN 'DEPOSIT' ELSE 'WITHDRAWAL' END,
CASE WHEN t.amount<0 THEN m.account_id END,CASE WHEN t.amount>0 THEN m.account_id END,ABS(t.amount),
CASE t.status WHEN 'POSTED' THEN 'SUCCESS' ELSE t.status END,SYS_EXTRACT_UTC(t.occurred_at),SYS_EXTRACT_UTC(t.occurred_at),t.merchant_name,t.category,t.payment_method
FROM legacy_transactions t JOIN banking_account_migration m ON m.legacy_id=t.bank_account_id;
ALTER TABLE transfers DROP CONSTRAINT fk_transfers_source_account;
ALTER TABLE transfers ADD migrated_account_id NUMBER;
UPDATE transfers t SET migrated_account_id=(SELECT account_id FROM banking_account_migration m WHERE m.legacy_id=t.source_account_id);
ALTER TABLE transfers MODIFY migrated_account_id NOT NULL;
ALTER TABLE transfers DROP COLUMN source_account_id;
ALTER TABLE transfers RENAME COLUMN migrated_account_id TO source_account_id;
ALTER TABLE transfers ADD CONSTRAINT fk_transfers_core_account FOREIGN KEY (source_account_id) REFERENCES accounts(id);
CREATE INDEX ix_transfers_core_source_status ON transfers(source_account_id,status);
ALTER TABLE banking_products DROP CONSTRAINT fk_products_owned_account;
ALTER TABLE banking_products ADD migrated_account_id NUMBER;
UPDATE banking_products p SET migrated_account_id=(SELECT account_id FROM banking_account_migration m WHERE m.legacy_id=p.account_id);
ALTER TABLE banking_products MODIFY migrated_account_id NOT NULL;
ALTER TABLE banking_products DROP COLUMN account_id;
ALTER TABLE banking_products RENAME COLUMN migrated_account_id TO account_id;
ALTER TABLE banking_products ADD CONSTRAINT fk_products_core_account FOREIGN KEY (account_id) REFERENCES accounts(id);
-- Update structured product and conversation references, including stored UI actions.
BEGIN
 FOR m IN (SELECT legacy_id,account_id FROM banking_account_migration) LOOP
  UPDATE banking_products SET payload=REPLACE(payload,m.legacy_id,TO_CHAR(m.account_id));
  UPDATE conversation_turns SET banking_content=REPLACE(banking_content,m.legacy_id,TO_CHAR(m.account_id)) WHERE banking_content IS NOT NULL;
 END LOOP;
END;
/
