import { useState } from "preact/hooks";
import { bankApi, Product, ProductKind } from "./api";
import { PageHeading, Panel, State, Status, Detail, useLoad } from "./ui";
import { formatMoney, formatDate, humanize, safeMask } from "../../services/banking-content";
export const productNames: Record<ProductKind, string> = { cards: "Cards", bills: "Bills", beneficiaries: "Payees", mandates: "Direct debits", loans: "Loans", "scheduled-payments": "Scheduled payments" };
const descriptions: Record<ProductKind, string> = { cards: "Your cards, balances and recorded activity.", bills: "Stay on top of amounts due and payment history.", beneficiaries: "Your verified payees and saved bank details.", mandates: "Track your recurring payment agreements.", loans: "Outstanding balances and upcoming instalments.", "scheduled-payments": "A clear view of payments scheduled for your accounts." };
export const productTitle = (p: Product) => p.displayName || p.billerName || p.payee || "Banking record";
function amount(p: Product) { if (p.cardType === "DEBIT")
    return undefined; return p.outstanding ?? p.amount ?? p.limit; }
export function ProductsPage({ token, kind, id }: {
    token: string;
    kind: ProductKind;
    id?: string;
}) {
    const [page, setPage] = useState(0);
    const [filter, setFilter] = useState("");
    const [search, setSearch] = useState("");
    const data = useLoad<Product | Product[]>(() => id ? bankApi.product(token, kind, id) : bankApi.products(token, kind, page, filter), [token, kind, id, page, filter]);
    const rows = Array.isArray(data.data) ? data.data : [];
    const detail = data.data && !Array.isArray(data.data) ? data.data : null;
    const visible = rows.filter(p => productTitle(p).toLowerCase().includes(search.toLowerCase()));
    return <><PageHeading title={id ? productNames[kind].replace(/s$/, "") + " details" : productNames[kind]} description={descriptions[kind]}/>
 {!id && <div class="bank-filters"><label class="bank-search-label">Find on this page<input type="search" placeholder={"Search " + productNames[kind].toLowerCase()} value={search} onInput={e => setSearch(e.currentTarget.value)}/></label>{kind !== "beneficiaries" && <label>Status<select value={filter} onChange={e => { setFilter(e.currentTarget.value); setPage(0); }}><option value="">All statuses</option>{(kind === "cards" ? ["ACTIVE", "BLOCKED", "CLOSED"] : kind === "bills" ? ["UPCOMING", "DUE", "OVERDUE", "PAID", "FAILED"] : kind === "mandates" ? ["ACTIVE", "PAUSED", "CANCELLED", "EXPIRED", "ACTION_REQUIRED"] : kind === "loans" ? ["ACTIVE", "CLOSED"] : ["SCHEDULED", "PENDING", "COMPLETED", "FAILED", "CANCELLED"]).map(s => <option value={s}>{humanize(s)}</option>)}</select></label>}</div>}
 <State loading={data.loading} error={data.error} retry={data.reload} empty={!data.loading && !data.error && !id && !visible.length ? "No " + productNames[kind].toLowerCase() + " to show" : undefined}>{detail ? <ProductDetail product={detail} kind={kind}/> : <div class={kind === "cards" ? "bank-card-grid" : "bank-product-grid"}>{visible.map(p => <a href={"#/" + kind + "/" + encodeURIComponent(p.id)} key={p.id} class={"bank-product " + (kind === "cards" ? "bank-payment-card" : "")}><header><span class="bank-tile-symbol" aria-hidden="true">{kind === "cards" ? "▰" : kind === "beneficiaries" ? productTitle(p).slice(0, 1).toUpperCase() : "↗"}</span><Status value={p.status}/></header><h2>{productTitle(p)}</h2><p>{p.numberMasked ? safeMask(p.numberMasked) : p.accountNumberMasked ? safeMask(p.accountNumberMasked) : p.reference || p.bankName || p.category || humanize(kind)}</p>{amount(p) !== undefined && <div class="bank-product-amount"><span>{kind === "cards" || kind === "loans" ? "Outstanding" : kind === "mandates" ? "Payment limit" : "Amount due"}</span><strong>{formatMoney(amount(p)!, p.currencyCode || "INR")}</strong></div>}<footer><span>{p.dueAt ? "Due " + formatDate(p.dueAt) : p.frequency ? humanize(p.frequency) : p.cardType ? humanize(p.cardType) + " card" : "View details"}</span><span aria-hidden="true">↗</span></footer></a>)}</div>}</State>
 {!id && kind !== "beneficiaries" && !data.loading && !data.error && <div class="bank-pagination"><span>Page {page + 1}</span><button disabled={!page} onClick={() => setPage(p => p - 1)}>← Previous</button><button disabled={rows.length < 12} onClick={() => setPage(p => p + 1)}>Next →</button></div>}
 <p class="bank-footnote">{kind === "beneficiaries" ? "Payees are provided by your bank. Adding or removing payees is not available online." : kind === "cards" ? "Card controls, PIN changes and replacement requests are not available online." : "These records are provided by your bank. Changes are not available online."}</p></>;
}
function ProductDetail({ product: p, kind }: {
    product: Product;
    kind: ProductKind;
}) {
    return <div class="bank-detail-grid"><Panel className="bank-product-summary"><span class="bank-tile-symbol">◇</span><h2>{productTitle(p)}</h2><Status value={p.status}/>{amount(p) !== undefined && <strong>{formatMoney(amount(p)!, p.currencyCode || "INR")}</strong>}<p>{p.numberMasked ? safeMask(p.numberMasked) : p.accountNumberMasked ? safeMask(p.accountNumberMasked) : p.reference}</p><a href={"#/" + kind}>← Back to {productNames[kind].toLowerCase()}</a></Panel><Panel title="Details"><dl>{p.bankName && <Detail label="Bank">{p.bankName}</Detail>}{p.cardType && <Detail label="Card type">{humanize(p.cardType)}</Detail>}{p.cardType !== "DEBIT" && p.availableLimit !== undefined && <Detail label="Available limit">{formatMoney(p.availableLimit, p.currencyCode)}</Detail>}{p.cardType !== "DEBIT" && p.creditLimit !== undefined && <Detail label="Credit limit">{formatMoney(p.creditLimit, p.currencyCode)}</Detail>}{p.cardType !== "DEBIT" && p.minimumPayment !== undefined && <Detail label="Minimum payment">{formatMoney(p.minimumPayment, p.currencyCode)}</Detail>}{p.dueAt && <Detail label="Due date">{formatDate(p.dueAt)}</Detail>}{p.nextDebit && <Detail label="Next debit">{formatDate(p.nextDebit)}</Detail>}{p.frequency && <Detail label="Frequency">{humanize(p.frequency)}</Detail>}{p.interestRate && <Detail label="Interest rate">{p.interestRate}%</Detail>}{p.nextEmi !== undefined && <Detail label="Next instalment">{formatMoney(p.nextEmi, p.currencyCode)}</Detail>}{p.accountId && <Detail label="Linked account"><a href={"#/accounts/" + encodeURIComponent(p.accountId)}>View account ↗</a></Detail>}{p.reference && <Detail label="Reference">{p.reference}</Detail>}</dl></Panel>
 {p.paymentHistory && <Panel title="Payment history"><State empty={!p.paymentHistory.length ? "No payments recorded" : undefined}>{p.paymentHistory.map(t => <div class="bank-record" key={t.id}><div><strong>{t.payee}</strong><small>{formatDate(t.dueAt)}</small></div><Status value={t.status}/><strong>{formatMoney(t.amount, t.currencyCode)}</strong></div>)}</State></Panel>}
 {p.transactions && <Panel title="Card activity"><State empty={!p.transactions.length ? "No card activity recorded" : undefined}>{p.transactions.map(t => <div class="bank-record" key={t.id}><div><strong>{t.merchantName || t.type}</strong><small>{formatDate(t.occurredAt)}</small></div><Status value={t.status}/><strong>{formatMoney(t.amount, t.currencyCode, true)}</strong></div>)}</State></Panel>}</div>;
}
