package com.nexa.api.nlp;

public enum Intent {
  GET_BALANCE,
  GET_ACCOUNTS,
  GET_RECENT_TRANSACTIONS,
  GET_TRANSACTION_DETAIL,
  GET_MANDATES,
  GET_MANDATE_DETAIL,
  GET_BILLS,
  GET_BILL_DETAIL,
  GET_CARDS,
  GET_CREDIT_CARDS,
  GET_CARD_TRANSACTIONS,
  GET_BENEFICIARIES,
  GET_SCHEDULED_PAYMENTS,
  GET_LOANS,
  GET_LOAN_DETAIL,
  START_TRANSFER,
  TRANSFER_STATUS,
  PAY_BILL,
  CANCEL_MANDATE,
  PAY_CARD,
  HELP,
  UNKNOWN
}
